name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The expected version to publish'
        required: true
        type: string
      action_id:
        description: 'GitHub Actions run ID to inspect'
        required: true
        type: string

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: List artifacts
        run: ./publish-release.sh ${{ inputs.version }} ${{ inputs.action_id }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
