name: Create Release

on:
  workflow_dispatch:
    inputs:
      action_id:
        description: 'GitHub Actions run ID to inspect'
        required: true
        type: string

jobs:
  list-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: List artifacts
        run: |
          repos/openziti/desktop-edge-win/actions/runs/16061692866/artifacts --jq '.artifacts[].name'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
